cciw/bookings/urls.py
from django.urls import path, re_path
from django.views.generic import RedirectView

from . import views
from .decorators import booking_account_optional

# The views mounted here relate only to end-user booking pages and
# functionality. Staff management of bookings is done in cciw.officers.views

urlpatterns = [
    path("", views.index, name="cciw-bookings-index"),
    path("start/", views.start, name="cciw-bookings-start"),
    path("email-sent/", views.email_sent, name="cciw-bookings-email_sent"),
    path("email-resent/", views.link_expired_email_sent, name="cciw-bookings-link_expired_email_sent"),
    path("v/", views.verify_and_continue, name="cciw-bookings-verify_and_continue"),
    path("verify-failed/", views.verify_email_failed, name="cciw-bookings-verify_email_failed"),
    re_path(
        r"^v/.+/$", booking_account_optional(RedirectView.as_view(pattern_name="cciw-bookings-verify_email_failed"))
    ),
    re_path(
        r"^p/.+/$", booking_account_optional(RedirectView.as_view(pattern_name="cciw-bookings-verify_email_failed"))
    ),
    path("account/", views.account_details, name="cciw-bookings-account_details"),
    path("loggedout/", views.not_logged_in, name="cciw-bookings-not_logged_in"),
    path("add-camper-details/", views.add_place, name="cciw-bookings-add_place"),
    path("edit-camper-details/<int:booking_id>/", views.edit_place, name="cciw-bookings-edit_place"),
    path("places-json/", views.places_json, name="cciw-bookings-places_json"),
    path("account-json/", views.account_json, name="cciw-bookings-account_json"),
    path("place-availability-json/", views.place_availability_json, name="cciw-bookings-place_availability_json"),
    path("checkout/", views.list_bookings, name="cciw-bookings-list_bookings"),
    path("pay/", views.pay, name="cciw-bookings-pay"),
    path("pay/done/", views.pay_done, name="cciw-bookings-pay_done"),
    path("pay/cancelled/", views.pay_cancelled, name="cciw-bookings-pay_cancelled"),
    path("overview/", views.account_overview, name="cciw-bookings-account_overview"),
]

cciw/cciwmain/urls.py
from django.urls import path

from cciw.cciwmain.views import camps as camp_views
from cciw.cciwmain.views import sites as sites_views
from cciw.sitecontent import views as sitecontent_views

from . import views

urlpatterns = [
    # Camps
    path("thisyear/", camp_views.thisyear, name="cciw-cciwmain-thisyear"),
    path("camps/", camp_views.index, name="cciw-cciwmain-camps_index"),
    path("camps/<yyyy:year>/", camp_views.index, name="cciw-cciwmain-camps_year_index"),
    path("camps/<yyyy:year>/<slug:slug>/", camp_views.detail, name="cciw-cciwmain-camps_detail"),
    # Sites
    path("sites/", sites_views.index, name="cciw-cciwmain-sites_index"),
    path("sites/<slug:slug>/", sites_views.detail, name="cciw-cciwmain-sites_detail"),
    path("404/", views.show404, name="cciw-404"),
    path("500/", views.show500, name="cciw-500"),
    # Site content
    path("", sitecontent_views.home, name="cciw-cciwmain-sitecontent_home"),
    # Fallback -- allows any other URL to be defined as arbitary pages.
    # htmlchunk.find will throw a 404 for any URL not defined.
    path("<path:path>/", sitecontent_views.find, name="cciw-cciwmain-sitecontent_find"),
]

cciw/mail/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path(r"ses-incoming-notification/", views.ses_incoming_notification, name="cciw-ses-incoming-notification"),
    path(r"ses-bounce/", views.ses_bounce_notification, name="cciw-ses-bounce"),
]

cciw/urls.py
import django.contrib.auth.views
import django.contrib.staticfiles.views
import django.views.static
from decorator_include import decorator_include
from django.conf import settings
from django.contrib import admin
from django.http import HttpResponse
from django.urls import include, path, register_converter

import cciw.officers.views
from cciw.bookings.decorators import check_booking_decorator

from . import converters

handler404 = "cciw.cciwmain.views.handler404"

register_converter(converters.FourDigitYearConverter, "yyyy")
register_converter(converters.TwoDigitMonthConverter, "mm")
register_converter(converters.CampIdConverter, "campid")
register_converter(converters.CampIdListConverter, "campidlist")
register_converter(converters.OptInt, "optint")


urlpatterns = [
    path("health-check/", lambda request: HttpResponse("OK")),
    # Plug in the password reset views (before 'admin')
    path("admin/password_reset/", cciw.officers.views.cciw_password_reset, name="admin_password_reset"),
    path(
        "admin/password_reset/done/",
        django.contrib.auth.views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        django.contrib.auth.views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("reset/done/", django.contrib.auth.views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    # Other 3rd party views
    path("captcha/", include("captcha.urls")),
    path("admin/", admin.site.urls),
    # Our normal views
    path("booking/", decorator_include([check_booking_decorator], "cciw.bookings.urls")),
    path("officers/", include("cciw.officers.urls")),
    path("notifications/", include("django_nyt.urls")),
    path("wiki/", include("wiki.urls")),
    path("paypal/ipn/", include("paypal.standard.ipn.urls")),
    path("mail/", include("cciw.mail.urls")),
    path("contact/", include("cciw.contact_us.urls")),
    path("documents/", include("cciw.documents.urls")),
]

if settings.DEVBOX:
    import debug_toolbar
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += [
        path("usermedia/<path:path>", django.views.static.serve, {"document_root": settings.MEDIA_ROOT}),
    ]

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += [path("django_functest/", include("django_functest.urls"))]

    if settings.DEBUG and "debug_toolbar" in settings.INSTALLED_APPS:
        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls)),
        ] + urlpatterns

urlpatterns = urlpatterns + [path("", include("cciw.cciwmain.urls"))]

cciw/accounts/models.py
"""
User accounts for staff
"""
import logging

import yaml
from django.conf import settings
from django.contrib import auth
from django.contrib.auth.models import AbstractBaseUser, Permission
from django.contrib.auth.models import UserManager as UserManagerDjango
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.db import models, transaction
from django.utils import timezone
from django.utils.functional import cached_property

# These names need to be synced with /config/static_roles.yaml
WIKI_USERS_ROLE_NAME = "Wiki users"
SECRETARY_ROLE_NAME = "Secretaries"
DBS_OFFICER_ROLE_NAME = "DBS Officers"
COMMITTEE_ROLE_NAME = "Committee"
BOOKING_SECRETARY_ROLE_NAME = "Booking secretaries"
REFERENCE_CONTACT_ROLE_NAME = "Safeguarding co-ordinators"
TREASURER_ROLE_NAME = "Treasurers"

CAMP_MANAGER_ROLES = [SECRETARY_ROLE_NAME, COMMITTEE_ROLE_NAME, BOOKING_SECRETARY_ROLE_NAME]

WIKI_ROLES = [WIKI_USERS_ROLE_NAME, COMMITTEE_ROLE_NAME, BOOKING_SECRETARY_ROLE_NAME, SECRETARY_ROLE_NAME]


# TODO:
# We need better terminology to distinguish:
# 1) users designated as 'admin' for a camp
# 2) users with admin rights for a camp (includes 1. above and leaders)
# 3) users with general admin rights (includes committee, secretaries)


logger = logging.getLogger(__name__)


def active_staff(user):
    return user.is_staff and user.is_active


def user_has_role(user, role_names):
    if len(role_names) == 0:
        return False
    # We generally use this multiple times, so it is usually going to be much
    # faster to fetch and cache all the roles once if not already fetched.
    roles = None
    if hasattr(user, "_prefetched_objects_cache"):
        if "roles" in user._prefetched_objects_cache:
            roles = user._prefetched_objects_cache["roles"]
    else:
        user._prefetched_objects_cache = {}
    if roles is None:
        roles = user.roles.all()
        # Evaluate:
        list(roles)
        user._prefetched_objects_cache["roles"] = roles

    return any(role.name == name for name in role_names for role in roles)


def get_camp_manager_role_users():
    """
    Returns all users who are in the 'camp admin' roles
    """
    return User.objects.filter(roles__in=Role.objects.filter(name__in=CAMP_MANAGER_ROLES))


def get_role_users(role_name):
    return Role.objects.get(name=role_name).members.all()


def get_role_email_recipients(role_name):
    return Role.objects.get(name=role_name).email_recipients.all()


def get_reference_contact_users():
    users = get_role_users(REFERENCE_CONTACT_ROLE_NAME)
    for user in users:
        if not user.contact_phone_number:
            logger.error("No contact_phone_number defined for reference contact user %s id %s", user.username, user.id)
    return users


class UserQuerySet(models.QuerySet):
    def older_than(self, before_datetime):
        return self.filter(date_joined__lt=before_datetime)


class UserManager(UserManagerDjango.from_queryset(UserQuerySet)):
    pass


# Our model is similar to AbstractUser, but our permissions are a bit different:
# we don't have user level permissions, and we have our custom 'Role' instead of
# 'Group' (and the M2M is on Role instead of User). So we inherit from
# AbstractBaseUser instead, and copy-paste some fields and methods


class User(AbstractBaseUser):
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        max_length=150,
        unique=True,
        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
        validators=[username_validator],
        error_messages={
            "unique": "A user with that username already exists.",
        },
    )
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=150, blank=True)
    email = models.EmailField("email address", blank=True)
    is_staff = models.BooleanField(
        "staff status",
        default=False,
        help_text="Designates whether the user can log into this admin site.",
    )
    is_active = models.BooleanField(
        "active",
        default=True,
        help_text="Designates whether this user should be treated as active. "
        "Unselect this instead of deleting accounts.",
    )
    date_joined = models.DateTimeField(default=timezone.now)
    is_superuser = models.BooleanField(
        "superuser status",
        default=False,
        help_text="Designates that this user has all permissions without " "explicitly assigning them.",
    )

    contact_phone_number = models.CharField(
        "Phone number",
        max_length=40,
        blank=True,
        help_text="Required only for staff like CPO who need to be contacted.",
    )

    bad_password = models.BooleanField(default=False)
    password_validators_used = models.TextField(blank=True)

    erased_on = models.DateTimeField(null=True, blank=True, default=None)

    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    class Meta:
        pass

    def __str__(self):
        return f"{self.full_name} <{self.email}>"

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}".strip()

    # Methods copied from AbstractUser
    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        return self.full_name

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    # Permissions methods, similar to those in PermissionsMixin
    def get_all_permissions(self, obj=None):
        permissions = set()
        for backend in auth.get_backends():
            permissions.update(backend.get_all_permissions(self, obj))
        return permissions

    def has_perm(self, perm, obj=None):
        """
        Return True if the user has the specified permission. Query all
        available auth backends, but return immediately if any backend returns
        True. Thus, a user who has permission from a single auth backend is
        assumed to have permission in general. If an object is provided, check
        permissions for that object.
        """
        # Active superusers have all permissions.
        if self.is_active and self.is_superuser:
            return True

        if perm == "wiki.moderate" and self.is_active and self.is_wiki_user:
            # There is some code in django-wiki that:
            # 1. checks for this permission
            #
            # 2. if it fails goes on to do a query that fails for us,
            #    due to the fact that we have 'Role' and not 'Group', and the
            #    different schema.
            #
            # So we avoid the bug by shortcutting here
            return True

        # Otherwise we need to check the backends.
        for backend in auth.get_backends():
            if not hasattr(backend, "has_perm"):
                continue
            try:
                if backend.has_perm(self, perm, obj):
                    return True
            except PermissionDenied:
                return False
        return False

    def has_perms(self, perm_list, obj=None):
        """
        Return True if the user has each of the specified permissions. If
        object is passed, check if the user has all required perms for it.
        """
        return all(self.has_perm(perm, obj) for perm in perm_list)

    def has_module_perms(self, app_label):
        """
        Return True if the user has any permissions in the given app label.
        Use similar logic as has_perm(), above.
        """
        # Active superusers have all permissions.
        if self.is_active and self.is_superuser:
            return True

        for backend in auth.get_backends():
            if not hasattr(backend, "has_module_perms"):
                continue
            try:
                if backend.has_module_perms(self, app_label):
                    return True
            except PermissionDenied:
                return False
        return False

    # Login/password related

    def mark_password_validation_done(self):
        self.password_validators_used = _current_password_validators_as_string()

    def mark_password_validation_not_done(self):
        self.password_validators_used = ""

    def password_validation_needs_checking(self):
        return self.password_validators_used != _current_password_validators_as_string()

    def set_password(self, password):
        retval = super().set_password(password)
        # To avoid getting stuck on set password page,
        # we have to clear this flag
        self.clear_bad_password()
        return retval

    def mark_bad_password(self):
        self.bad_password = True
        self.mark_password_validation_done()

    def clear_bad_password(self):
        self.bad_password = False
        self.mark_password_validation_done()

    # Helpers for roles
    @cached_property
    def is_booking_secretary(self):
        if not active_staff(self):
            return False
        return user_has_role(self, [BOOKING_SECRETARY_ROLE_NAME])

    @cached_property
    def is_treasurer(self):
        if not active_staff(self):
            return False
        return user_has_role(self, [TREASURER_ROLE_NAME])

    @cached_property
    def is_camp_admin(self):
        """
        Returns True if the user is an admin for any camp, or has rights
        for editing camp/officer/reference/DBS information

cciw/cciwmain/views/sites.py
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse

from cciw.cciwmain.models import Site


def index(request):
    return TemplateResponse(
        request,
        "cciw/sites/index.html",
        {
            "title": "Camp sites",
            "sites": Site.objects.all(),
        },
    )


def detail(request, slug: str):
    return TemplateResponse(
        request,
        "cciw/sites/detail.html",
        {
            "site": get_object_or_404(Site.objects.filter(slug_name=slug)),
        },
    )

cciw/documents/views.py
from django.apps import apps
from django.http import Http404, HttpResponse

from .models import Document


def not_found():
    return Http404("Document not found, or insufficient privileges to view it.")


def download(request, app_label: str, model_name: str, id: int):
    try:
        model = apps.get_model(app_label, model_name)
    except LookupError:
        raise not_found()

    if not model.__base__ == Document:
        raise not_found()

    perm = f"{app_label}.view_{model_name}"
    if not request.user.has_perm(perm):
        raise not_found()

    obj = model.objects.get(id=id)

    return HttpResponse(
        content=obj.content,
        content_type=obj.mimetype,
        headers={"Content-Length": obj.size, "Content-Disposition": f'attachment; filename="{obj.filename}"'},
    )

templates/cciw/bookings/account_details.html
{% extends 'cciw/bookings/standard.html' %}
{% block content %}

  <p>Please enter your name and address - we will use these to send you
    information about camp. You may also choose to receive other communications
    from us. Note that we do not pass on any details to third parties, except as
    indicated.</p>

  <form id='id_accountdetails' action="" method="POST" class="ajaxify">
    {% csrf_token %}
    {{ form.as_p }}

    <div class='mailchimp-notice'>Email newsletter: we use a third party email
      service provider, MailChimp, to send you these newsletter emails. We
      provide MailChimp with only your email address. MailChimp treats
      information about you in accordance with the provisions of its <a href='https://mailchimp.com/legal/privacy/'>Privacy
        Policy</a>. MailChimp also utilizes certain technologies, such as pixels
      and web beacons, in the emails that are sent through MailChimp. These
      technologies allow MailChimp to track whether you have opened or clicked
      on our emails and if so, the date, time, and IP address associated with
      the open and/or click. For more information on MailChimp's use of these
      technologies, you can read their
      <a href='https://mailchimp.com/legal/cookies/'>Cookie Statement</a>.
    </div>

    <div class="formrow">
      <br/>
      <input type="submit" name="submit" value="Save and continue" />
    </div>
  </form>


  <p><br/><br/>If you need to change the email address on your account, please <a href="{% url 'cciw-contact_us-send' %}?bookings">contact us</a>.

{% endblock %}

templates/cciw/bookings/account_overview.html
{% extends 'cciw/bookings/standard.html' %}
{% block content %}

  <section class="grouped">
    <h1>Your details</h1>

    <div class="actiongroup">
      <div class="actioninfo">
        {% with account=request.booking_account %}
          <table class="sideheaders">
            <tr>
              <th>Name</th>
              <td>{{ account.name }}</td>
            </tr>
            <tr>
              <th>Email</th>
              <td>{{ account.email }}</td>
            </tr>
            <tr>
              <th>Address</th>
              <td>{{ account.get_address_display|linebreaksbr }}</td>
            </tr>
            <tr>
              <th>Post code</th>
              <td>{{ account.address_post_code }}</td>
            </tr>
          </table>
        {% endwith %}
      </div>
      <div class="actionbutton">
        <a href="{% url 'cciw-bookings-account_details' %}" class="bigaction">Update details</a>
      </div>
    </div>
  </section>

  <section class="grouped">
    <h1>Your places {{ thisyear }}</h1>

    {% if confirmed_places %}
      <h2>Confirmed places</h2>
      <p>You have the following confirmed places on camps this year:</p>

      {% with bookings=confirmed_places show_missing_agreements=True %}
        {% include "cciw/bookings/place_table.html" %}
      {% endwith %}

      <p>Information about what to bring on camp will be sent in an email or letter
        before camp.</p>

    {% endif %}

    {% if unconfirmed_places %}
      <h2>Booked places</h2>

      <p>The following places are booked, but will expire soon unless you pay:</p>

      <div class="actiongroup">
        <div class="actioninfo">
          {% with bookings=unconfirmed_places show_missing_agreements=True %}
            {% include "cciw/bookings/place_table.html" %}
          {% endwith %}
        </div>
        {% include "cciw/bookings/pending_payment_notice.html" %}
        <div class="actionbutton">
          <a href="{% url 'cciw-bookings-pay' %}" class="bigaction">Pay</a>
        </div>
      </div>
    {% endif %}

    {% if basket_or_shelf %}
      <h2>Basket / shelf</h2>

      <p>These places are <b>not booked</b>:</p>

      <div class="actiongroup">
        <div class="actioninfo">
          {% with bookings=basket_or_shelf %}
            {% include "cciw/bookings/place_table.html" %}
          {% endwith %}
        </div>
        <div class="actionbutton">
          <a href="{% url 'cciw-bookings-list_bookings' %}" class="bigaction">Review and book</a>
        </div>
      </div>
    {% endif %}

    {% if cancelled_places %}
      <h2>Cancelled places</h2>

      {% with bookings=cancelled_places %}
        {% include "cciw/bookings/place_table.html" %}
      {% endwith %}
    {% endif %}

    {% if not confirmed_places and not unconfirmed_places and not cancelled_places and not basket_or_shelf %}
      <div class="actionsplit">
        <div class="actionbutton">
          <a href="{% url 'cciw-bookings-add_place' %}" class="bigaction">Add new booking</a>
        </div>
        <div class="actioninfo">
          <p>You do not have any bookings entered for this year. Press the button to begin.</p>
        </div>
      </div>
    {% else %}
      <h2>More places</h2>

      <div class="actionsplit">
        <div class="actionbutton">
          <a href="{% url 'cciw-bookings-add_place' %}" class="bigaction">Add new booking</a>
        </div>
        <div class="actioninfo">
          <p>Press the button and enter camper details to book another place on camp.</p>
        </div>
      </div>
    {% endif %}
  </section>

  <section class="grouped">
    <h1>Balance</h1>

    {% if balance_full <= 0 %}
      <p>You have nothing to pay.</p>
    {% else %}
      <div class="actionsplit">
        <div class="actionbutton">
          <a class="bigaction" href="{% url 'cciw-bookings-pay' %}">Pay</a>
        </div>
        <div class="actioninfo">
          <p>Your total balance is: £{{ balance_full }}</p>
          {% if balance_due_now != balance_full %}
            <p>Balance currently due: £{{ balance_due_now }}</p>
          {% endif %}
        </div>
      </div>
    {% endif %}
    {% include "cciw/bookings/pending_payment_notice.html" %}
  </section>

  <section class="grouped">

    <h1>Logging out</h1>

    <p><strong>In order to log back in again, you will need to verify your email address as
      you did the first time.</strong></p>

    <p>By logging out, other users of this computer will not be able to access your
      account details, which is important if you are using a public computer (for
      example in an internet cafe).</p>

    <p>Press this button in order to go ahead and log out:</p>

    <form action="" method="POST">
      {% csrf_token %}
      <p style="text-align: center">
        <input type="submit" name="logout" value="Log out" class="bigaction">
      </p>
    </form>

    <p>Otherwise your session will expire two weeks after you last logged in.</p>

  </section>

  {% include 'cciw/bookings/help.html' %}

{% endblock %}

templates/cciw/bookings/bookingbar.html
<div id="bookingbar">
  <nav>
    {% spaceless %}
      <ul>
        {% for name, caption, is_link, url, msg in stages %}
          <li>
            {% if is_link and name != current_stage %}
              <a href="{{ url }}">{{ caption }}</a>
            {% elif name == current_stage %}
              <span aria-current="step">{{ caption }}</span>
            {% else %}
              <span title="{{ msg }}">{{ caption }}</span>
            {% endif %}
          </li>
        {% endfor %}
      </ul>
    {% endspaceless %}
  </nav>
</div>

templates/cciw/bookings/email_sent.html
{% extends "cciw/bookings/standard.html" %}
{% block content %}
  {% if link_expired %}
    <p><b>The link you used for logging in has expired.</b></p>

    <p>We have sent you a new email with a new login link. Please use the login
      link in the email to continue the booking and payment process process.
      This must be done within a few days or the link will expire again.
    </p>

  {% else %}
    <p>An email has been sent to your address to verify that it works. Please
      use the login link in the email to continue the booking and payment
      process. This must be done within a few days or the link will expire.
    </p>
  {% endif %}

{% endblock %}

templates/cciw/bookings/email_verification_failed.html
{% extends "cciw/bookings/standard.html" %}
{% block content %}
  <p>The verification token was not correct, and your email
    address has not been verified. Please ensure you copied the full URL
    (link) from the email into your browser, or
    <a href="{% url 'cciw-bookings-start' %}">try again</a>.</p>
{% endblock %}

templates/cciw/bookings/help.html
<h2>Help</h2>

<p>If you have a query about a booking, please
  <a href="{% url 'cciw-contact_us-send' %}?bookings">contact the booking
    secretary</a>. </p>

<p>If you are having a problem with the website itself, please
  <a href="{% url 'cciw-contact_us-send' %}?website">contact the
    webmaster</a>. </p>

templates/cciw/bookings/not_logged_in.html
{% extends 'cciw/standard.html' %}
{% block content %}
  <p>You are not logged in to the booking system — either you do not have an
    account or your session has expired. You will need to
    <a href="{% url 'cciw-bookings-start' %}">enter and verify your email
      address</a> to
    continue.</p>

{% endblock %}

templates/cciw/bookings/pay_cancelled.html
{% extends 'cciw/bookings/standard.html' %}
{% block content %}
  <h3>Payment cancelled</h3>

  <p>You cancelled your payment. Please ensure you
    <a href="{% url 'cciw-bookings-pay' %}">pay</a> within 24 hours, or your
    booking will expire and the place can be taken by someone else.
  </p>


{% endblock %}

templates/cciw/bookings/pending_payment_notice.html
{% if pending_payment_total > 0 %}
  <div>
    <p><b>PLEASE NOTE:</b> Before making additional payments, remember
      that you have some payments that are waiting for confirmation,
      totalling £{{ pending_payment_total }}.</p>
  </div>
{% endif %}

templates/cciw/bookings/standard.html
{% extends 'cciw/standard.html' %}
{% load bookings %}

{% block bodyattr %}class="bookingspage"{% endblock %}

{% block pagetitle %}Booking{% endblock %}

{% block pagetitlediv %}
  {{ block.super }}
  {% bookingbar %}
{% endblock %}

templates/cciw/bookings/start.html
{% extends "cciw/bookings/standard.html" %}
{% block content %}

  <p>This is the starting point for <b>booking</b> camper places online, and <b>paying</b>
    online. If you are wanting to come on camp as a leader/officer, this booking
    system is not for you – please see the <a href="/helpers/officers/">leaders and officers</a> section.</p>


  {% if not booking_open %}
    <p><strong>PLEASE NOTE: Booking is not yet open for this year — you will not be
      able to complete the booking process at this stage.</strong></p>
  {% endif %}

  {% if booking_open and not any_bookings_possible %}
    <p><strong>No places are available on any camps! You may continue, but you
      will only be able to complete the booking process for a new place on a
      camp if you can arrange an exception with the camp leaders.</strong></p>
  {% endif %}

  <p>To book online, you must have a <b>credit card, debit card, or Paypal account</b>,
    and must not be a minor.</p>

  <p>To get started, we first need your <b>email address</b>. Note - this is the
    email address of the person booking and paying, not of the camper. We will
    send an email to this address to confirm it is correct and log you in.</p>

  <form method="POST" action="">
    {% csrf_token %}
    <div class="field">
      <label class="required" for="id_email">Email address:</label>
      {{ form.email }}
      <input type="submit" name="submit" value="Submit" />
    </div>
  </form>
  <br>
  <p>If you have trouble receiving the email, you may need to <a href="/website/help/whitelist-email/">whitelist our email address</a>
    <strong>noreply@cciw.co.uk</strong> or our emails might be classified as junk mail.</p>

{% endblock %}

templates/cciw/bookings/use_previous_popup_inc.html
<div id="id_use_existing_data_popup" class="inlinepopup" style="display:none;">
  <div class="closebar">
    <a href="#" id="id_popup_close_btn">Close</a>
  </div>
  <div class="popupbody">
    <p>You can copy information previously entered to save time. Please note:</p>

    <ul>
      <li>This will overwrite existing data on this form!</li>
      <li><strong>Remember to check the data after using this to ensure it is all up to date,
        and fill in any new fields that have been added.</strong>
      </li>
    </ul>

    <div>
      Select previous booking to copy from:
    </div>
    <div style="text-align:center;">
      <form name="select_place">
        <select id="id_use_existing_select">
        </select>
      </form>
      <br>
    </div>
    <div>
      Choose which information to copy:
    </div>
    <div style="text-align:center;">
      <input type="submit" id="id_use_all_btn" value="Use all personal information" /> <br/>
      <input type="submit" id="id_use_address_btn" value="Use address and contact information" /> <br/>
      <input type="submit" id="id_use_gp_info_btn" value="Use GP information" />
    </div>
  </div>
</div>

<div class="inlinepopup_background" id="id_popup_background"></div>